(SIMP-10436) Bug in openldap2ds389
simp/simp-utils pull request #37
Opened 2021-08-23 16:04 UTC by jeannegreulich

-  Add ou=People,<basedn> when converting a user cn to dn.  (It was
   using ou=Groups,<basedn>)

SIMP-10436 #close

2021-08-23 16:29 UTC, lnemsick-simp commented on share/transition_scripts/openldap_to_389ds/openldap_to_389ds.rb
> +      ldifs389[new_dn] = convert_group(attr, olduserdn)
Why was this not picked up by the acceptance tests?  Should the test be updated?

2021-08-24 13:12 UTC, trevor-vaughan requested changes
This needs to be reviewed more closely.

It looks like the group conversion is now being used on users instead of groups.

2021-08-24 13:49 UTC, jeannegreulich commented
> This needs to be reviewed more closely.
> 
> It looks like the group conversion is now being used on users instead of groups.

The OU that is passed in is for the members of the group not the group so you need to pass in the People OU.  
This is the line where it is used:  
newattrs[:member] = newattrs[:memberuid].map { |u| "uid=#{u},#{userdn}" } if newattrs[:memberuid]

2021-08-24 17:48 UTC, trevor-vaughan approved these changes

2021-08-24 17:49 UTC, merged